### ISSUE TITLE
Implement submission of read-write transactions to `TransactionHandle`s

### ISSUE THREAD

**Issue by jorisdral** [input-output-hk/lmdb-simple#14]
#13 introduces `TransactionHandle`s, but currently only read-only transactions can be submitted to them. We should implement submission of read-write transactions to `TransactionHandle`s as well.

**Comment by jorisdral** [comment]
We can currently not implement the submission of read-write transactions, because the lower-level Haskell bindings are set up in such a way that the internal `MDB_txn` should be created and completed in a single bound Haskell thread:

```haskell
-- | Begin a new transaction, possibly read-only, with a possible parent.
--
--     mdb_txn_begin env parent bReadOnly
--
-- NOTE: Unless your MDB_env was created with MDB_NOLOCK, it is necessary
-- that read-write transactions be created and completed in one Haskell
-- 'bound' thread, e.g. via forkOS or runInBoundThread. The bound threads
-- are necessary because LMDB uses OS-level mutexes which track the thread
-- ID of their owning thread.
--
-- This LMDB adapter includes its own MVar mutex to prevent more than one
-- Haskell-level thread from trying to write at the same time.
--
-- The hierarchical transactions are useful for read-write transactions.
-- They allow trying something out then aborting if it doesn't work. But
-- only one child should be active at a time, all in the same OS thread.
--
mdb_txn_begin :: MDB_env -> Maybe MDB_txn -> Bool -> IO MDB_txn
```

**Comment by jasagredo** [comment]
I think we can/should close this then for now, do we need it for anything in particular or will it just be a nice-to-have.

**Comment by jorisdral** [comment]
To close this, I think we should put a note in the `TransactionHandle` module that explains why only read-only transactions are enabled. I'll do that soon
